// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebAPI_24_03.Data;

#nullable disable

namespace MyWebAPI_24_03.Migrations
{
    [DbContext(typeof(MyDataModel1DbContext))]
    partial class MyDataModel1DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyWebAPI_24_03.Model1.APIConnect", b =>
                {
                    b.Property<int>("ConnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConnId"), 1L, 1);

                    b.Property<bool>("Conn")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordClient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserClient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ConnId");

                    b.ToTable("APIConnectDb");
                });

            modelBuilder.Entity("MyWebAPI_24_03.Model1.APIData", b =>
                {
                    b.Property<int>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DataId"), 1L, 1);

                    b.Property<bool>("CmdMotor")
                        .HasColumnType("bit");

                    b.Property<double>("DataLevel")
                        .HasColumnType("float");

                    b.Property<double>("DataTemperature")
                        .HasColumnType("float");

                    b.Property<string>("NameTank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StartStop")
                        .HasColumnType("bit");

                    b.Property<string>("TimeStanp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DataId");

                    b.ToTable("APIDataDb");
                });

            modelBuilder.Entity("MyWebAPI_24_03.Model1.APINameClient", b =>
                {
                    b.Property<int>("NameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NameId"), 1L, 1);

                    b.Property<string>("NameIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamePLC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("NameId");

                    b.ToTable("APINameClientDb");
                });
#pragma warning restore 612, 618
        }
    }
}
